name: Preparation

on
	push:
		branches: [ main ]
	pull request:
		branches: [ main ]

jobs:
	build:
		runs-on: ubuntu-latest

		steps:
			- uses: actions/checkout@v2

			- name: update articles
			- run: sh ./update_articles.sh