name: deployment workflow

on: [push, workflow_dispatch]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: update articles
        uses: actions/checkout@v2
        run: sh ./update_articles.sh

